### ISSUE TITLE
peek() at head or tail?

### ISSUE THREAD

**Issue by Humancell** [wizard97/ArduinoRingBuffer#9]
Thank you for the great work!  I'm just starting to do some development using this library, and so far so good ... except ...  :-)

I'm wanting to use peek() to look at the next element to be pulled from the queue ... but it requires a num ... and I don't know what that num is?  I can fetch the numelements() but that doesn't give it to me either.

Is there a way to find out what the "first" or "head" num is?  And in that case the "last" or "tail" might be useful also?

**Comment by wizard97** [comment]
Glad to hear it is working well for you!

`peek(&dest, 0)` will peek at the 0th element (the oldest valid element), and should do what you want to do. I should really have called num index.

Let me know if this works for you! Feel free to submit a pull request making this behavior clearer in the README.

**Comment by Humancell** [comment]
Thank you for the quick reply!  This makes more sense now.

So if I understand this correctly, index (num) 0 will *always* be the "next" item that will be returned with a call to pull().  If I add() three items (a, b, and c) then issue two pull() calls, "c" will be at index (num) 0?

As I get to learn more about this I'll fork and see if I can assist and create a pull request for you.

**Comment by wizard97** [comment]
Yeah, the index argument is the 0-indexed element in the queue, starting from the oldest valid element. Your example is correct, the 0th index will always be the oldest element.

**Comment by Humancell** [comment]
Thank you!
